<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="MAIN" Id="{9d67fa5f-b22b-413d-bd2f-078ef7b27582}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	eventEmitter_TestSuit : Disposable_TestSuit;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[TcUnit.RUN();]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>