<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="MockDisposable" Id="{b6dd5f4e-cd88-0ac7-1c7d-fe3141cbfa38}" SpecialFunc="None">
    <Declaration><![CDATA[{attribute 'linkalways'} 
{attribute 'no_explicit_call' := 'This FB is a CLASS and must be accessed using methods or properties'}
{attribute 'enable_dynamic_creation'}
FUNCTION_BLOCK MockDisposable EXTENDS Disposable
VAR
	disposedFlag : REFERENCE TO BOOL;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Folder Name="Constructor" Id="{53162d61-c8fa-0c98-298f-bdd8fb2ca230}" />
    <Method Name="FB_init" Id="{610da5a1-3b4a-0935-385a-dc588635f05c}" FolderPath="Constructor\">
      <Declaration><![CDATA[METHOD FB_init : BOOL
VAR_INPUT
	bInitRetains : BOOL; // if TRUE, the retain variables are initialized (warm start / cold start)
	bInCopyCode : BOOL;  // if TRUE, the instance afterwards gets moved into the copy code (online change)
	DisposedFlag : REFERENCE TO BOOL;
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[THIS^.disposedFlag REF= DisposedFlag;]]></ST>
      </Implementation>
    </Method>
    <Method Name="OnDispose" Id="{66d42422-07ef-0aac-08dc-54d96cf1e697}">
      <Declaration><![CDATA[METHOD PROTECTED OnDispose : BOOL
VAR_INPUT
	CalledExplicitly : BOOL; 
END_VAR

]]></Declaration>
      <Implementation>
        <ST><![CDATA[disposedFlag := TRUE;]]></ST>
      </Implementation>
    </Method>
  </POU>
</TcPlcObject>