<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="MockDisposable" Id="{b6dd5f4e-cd88-0ac7-1c7d-fe3141cbfa38}" SpecialFunc="None">
    <Declaration><![CDATA[{attribute 'linkalways'} 
{attribute 'no_explicit_call' := 'This FB is a CLASS and must be accessed using methods or properties'}
{attribute 'enable_dynamic_creation'}
FUNCTION_BLOCK MockDisposable EXTENDS Disposable
VAR
	disposedFlag : REFERENCE TO BOOL;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Folder Name="Constructor" Id="{53162d61-c8fa-0c98-298f-bdd8fb2ca230}" />
    <Folder Name="Destructor" Id="{8534e866-0d8b-4843-95b1-abd7bc1d43dc}" />
    <Method Name="FB_exit" Id="{0e91c4ee-35e1-4c12-affe-8655ee47ca02}" FolderPath="Destructor\">
      <Declaration><![CDATA[METHOD FB_exit : BOOL
VAR_INPUT
	bInCopyCode : BOOL; // if TRUE, the exit method is called for exiting an instance that is copied afterwards (online change).
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[disposedFlag := TRUE;]]></ST>
      </Implementation>
    </Method>
    <Method Name="FB_init" Id="{610da5a1-3b4a-0935-385a-dc588635f05c}" FolderPath="Constructor\">
      <Declaration><![CDATA[METHOD FB_init : BOOL
VAR_INPUT
	bInitRetains : BOOL; // if TRUE, the retain variables are initialized (warm start / cold start)
	bInCopyCode : BOOL;  // if TRUE, the instance afterwards gets moved into the copy code (online change)
	DisposedFlag : REFERENCE TO BOOL;
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[THIS^.disposedFlag REF= DisposedFlag;]]></ST>
      </Implementation>
    </Method>
  </POU>
</TcPlcObject>